version: '3'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: mbit
      MYSQL_USER: mbit
      MYSQL_PASSWORD: mbit
      MYSQL_DATABASE: pictures
    volumes:
      - ./database:/var/lib/mysql

  api:
    build: api_image
    ports:
      - 80:80
    volumes:
      - ./imagenes:/app/imagenes
    depends_on:
      - db
